services:
  db:
    image: postgres:15-alpine3.21
    container_name: postgres-database
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=db_backup_meta
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  dbbackup-cli:
    build: .
    container_name: dbbackup-cli-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_backup_meta
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
    entrypoint: tail -f /dev/null

  postgres_test:
    image: postgres:15-alpine
    container_name: dbbackup_postgres_test
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./sample-data/postgres:/docker-entrypoint-initdb.d

  mysql_test:
    image: mysql:8.0
    container_name: dbbackup_mysql_test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./sample-data/mysql:/docker-entrypoint-initdb.d

  mongo_test:
    image: mongo:6.0
    container_name: dbbackup_mongo_test
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_test_data:/data/db
      - ./sample-data/mongo:/docker-entrypoint-initdb.d

volumes:
  postgres_dev_data:
    driver: local
  postgres_test_data:
    driver: local
  mysql_test_data:
    driver: local
  mongo_test_data:
    driver: local
