version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: dbbackup_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_backup_meta
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_backup_meta"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbbackup_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_backup_meta
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
      # Activate the 'prod' profile to ensure it uses production-like settings
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  postgres_data:
    driver: local
