version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbbackup_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_backup_meta
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
      # Activate the 'prod' profile to ensure it uses production-like settings
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  postgres_data:
    driver: local
